Repository puppetlabs/pct, pull requests merged in 2021-08, with the labels that each got.

#177 (GH-172) Removal of PDKShell
  CHANGELOG.md
  cmd/bundle/bundle.go
  cmd/bundle/bundle_test.go
  cmd/console/console.go
  cmd/console/console_test.go
  cmd/convert/convert.go
  cmd/convert/convert_test.go
  cmd/env/env.go
  cmd/env/env_test.go
  cmd/get/config/config.go
  cmd/get/config/config_test.go
  cmd/get/get.go
  cmd/get/get_test.go
  cmd/release/prep/prep.go
  cmd/release/prep/prep_test.go
  cmd/release/publish/publish.go
  cmd/release/publish/publish_test.go
  cmd/release/release.go
  cmd/release/release_test.go
  cmd/remove/config/config.go
  cmd/remove/config/config_test.go
  cmd/remove/remove.go
  cmd/remove/remove_test.go
  cmd/set/config/config.go
  cmd/set/config/config_test.go
  cmd/set/set.go
  cmd/set/set_test.go
  cmd/test/test.go
  cmd/test/test_test.go
  cmd/test/unit/unit.go
  cmd/test/unit/unit_test.go
  cmd/update/update.go
  cmd/update/update_test.go
  cmd/validate/validate.go
  cmd/validate/validate_test.go
  go.mod
  internal/pkg/pdkshell/env_var.go
  internal/pkg/pdkshell/env_var_test.go
  internal/pkg/pdkshell/os_utils.go
  internal/pkg/pdkshell/path.go
  internal/pkg/pdkshell/path_test.go
  internal/pkg/pdkshell/path_windows.go
  internal/pkg/pdkshell/path_windows_test.go
  internal/pkg/pdkshell/pdkshell.go
  internal/pkg/pdkshell/pdkshell_test.go
  internal/pkg/pdkshell/pdkshell_windows_test.go
  internal/pkg/utils/utils.go
  internal/pkg/utils/utils_test.go
  main.go
Labels: enhancement

#170 Refactor of Internal/PKG
  acceptance/testutils/testutils.go
  cmd/build/build.go
  cmd/new/new.go
  go.mod
  internal/pkg/gzip/gunzip.go
  internal/pkg/gzip/gunzip_test.go
  internal/pkg/gzip/gunzip_utils.go
  internal/pkg/gzip/gzip.go
  internal/pkg/gzip/gzip_test.go
  internal/pkg/gzip/gzip_utils.go
  internal/pkg/mock/fileinfo.go
  internal/pkg/mock/gunzip.go
  internal/pkg/mock/gzip.go
  internal/pkg/mock/os_utils.go
  internal/pkg/mock/tar.go
  internal/pkg/mock/utilsHelper.go
  internal/pkg/pct/build.go
  internal/pkg/pct/build_test.go
  internal/pkg/pct/gzip_utils_mock.go
  internal/pkg/pct/install.go
  internal/pkg/pct/install_test.go
  internal/pkg/pct/io_utils_mock.go
  internal/pkg/pct/os_utils_mock.go
  internal/pkg/pct/pct.go
  internal/pkg/pct/pct_test.go
  internal/pkg/pct/tar_utils_mock.go
  internal/pkg/tar/tar.go
  internal/pkg/tar/tar_test.go
  internal/pkg/tar/tar_utils.go
  internal/pkg/tar/untar.go
  internal/pkg/tar/untar_test.go
  internal/pkg/tar/untar_utils.go
  internal/pkg/utils/io_utils.go
  internal/pkg/utils/os_utils.go
  internal/pkg/utils/utils.go
  internal/pkg/utils/utilsHelper.go
Labels: maintenance

#186 (MAINT) Add GH-144 entry to CHANGELOG
  CHANGELOG.md
Labels: documentation, maintenance

#187 0.3.0 Release Prep
  CHANGELOG.md
  README.md
  cmd/root/root.go
  cmd/version/version.go
Labels: maintenance

#188 (MAINT) Fix 0.3.0 CHANGELOG entry
  CHANGELOG.md
Labels: maintenance

#179 (GH-167) Add `pct install` CLI command
  CHANGELOG.md
  acceptance/install/install_test.go
  acceptance/install/testdata/additional-project.tar.gz
  acceptance/install/testdata/good-project.tar.gz
  acceptance/install/testdata/invalid-gz-project.tar.gz
  acceptance/install/testdata/invalid-tar-project.tar.gz
  cmd/install/install.go
  cmd/install/install_test.go
  cmd/new/new.go
  internal/pkg/mock/install.go
  internal/pkg/pct/install.go
  internal/pkg/pct/install_test.go
  internal/pkg/tar/tar.go
  internal/pkg/utils/utils.go
  main.go
Labels: enhancement

#195 (MAINT) Change `Mkdir(All)?` perms from 750 -> 0750
  internal/pkg/pct/build_test.go
  internal/pkg/pct/pct_test.go
  internal/pkg/tar/tar_test.go
Labels: maintenance

#196 (GH-182) Add author to template display
  acceptance/install/install_test.go
  acceptance/install/testdata/additional-project.tar.gz
  acceptance/install/testdata/good-project.tar.gz
  acceptance/new/new_test.go
  cmd/new/new.go
  internal/pkg/pct/pct.go
  internal/pkg/pct/pct_test.go
Labels: enhancement
