Repository puppetlabs/pct, pull requests merged in 2021-06, with the labels that each got.

#74 (GH-64) Strip pct from command name
  internal/pkg/pdkshell/pdkshell.go
  internal/pkg/utils/utils.go
Labels: bug

#75 (GH-65) Allow deployment of empty files
  .gitignore
  internal/pkg/pct/pct.go
  internal/pkg/pct/pct_test.go
  internal/pkg/pct/testdata/examples/good-project/content/empty.txt
Labels: bug

#76 (GH-14) Return the exit code from the PDK when executed by the wrapper
  internal/pkg/pdkshell/pdkshell.go
Labels: enhancement

#79 (maint) fix help docs for completion
  cmd/completion/completion.go
Labels: maintenance

#68 (GH-67) Add installation scripts for PCT
  tools/install.ps1
  tools/install.sh
Labels: enhancement

#86 (maint) Update CHANGELOG
  CHANGELOG.md
Labels: maintenance

#81 (GH-77) Add information on how to file feedback
  .github/ISSUE_TEMPLATE/config.yml
  README.md
Labels: maintenance

#102 (MAINT) Release prep 0.1.0
  CHANGELOG.md
Labels: maintenance

#104 (MAINT) Correct arg ordering for assert.Equal in new_test.go
  acceptance/new_test.go
Labels: maintenance

#105 (GH-107) Initialize zerolog via cobra.OnInitialize method
  cmd/root/root.go
  main.go
Labels: bug

#58 (maint) Add additional quality checks via gh actions
  .github/workflows/codequality.yml
  .goreleaser.yml
  Makefile
  acceptance/new_test.go
  acceptance/testutils/testutils.go
  cmd/build/build_test.go
  cmd/bundle/bundle_test.go
  cmd/completion/completion.go
  cmd/convert/convert_test.go
  cmd/env/env_test.go
  cmd/get/config/config_test.go
  cmd/get/get_test.go
  cmd/new/new.go
  cmd/release/prep/prep_test.go
  cmd/release/publish/publish_test.go
  cmd/remove/config/config_test.go
  cmd/remove/remove_test.go
  cmd/root/root.go
  cmd/set/config/config.go
  cmd/set/set_test.go
  cmd/test/test_test.go
  cmd/update/update_test.go
  cmd/validate/validate_test.go
  go.mod
  go.sum
  internal/pkg/pct/pct.go
  internal/pkg/pct/pct_test.go
Labels: maintenance

#124 (GH-125) Fix `$ver` bug in download script
  tools/install.sh
Labels: bug

#123 (maint) Apply go fmt suggestions
  internal/pkg/pct/pct_test.go
Labels: maintenance

#126 (maint) ensure code quality check run the correct version of go
  .github/workflows/codequality.yml
Labels: maintenance

#114 (maint) Update getting started
  README.md
Labels: documentation

#135 (GH-15) Unset necessary env vars in pdkshell
  internal/pkg/pdkshell/env_var.go
  internal/pkg/pdkshell/env_var_test.go
  internal/pkg/pdkshell/os_utils.go
  internal/pkg/pdkshell/pdkshell.go
Labels: bug

#138 (maint) Update CHANGELOG for 0.2.0
  CHANGELOG.md
Labels: documentation, maintenance

#139 (GH-139) Fix version command release output
  cmd/version/version.go
Labels: bug

#140 Create dependabot.yml
  .github/dependabot.yml
Labels: maintenance

#141 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: maintenance
