Repository puppetlabs/pct, pull requests merged in 2021-05, with the labels that each got.

#2 Puppet Content Template system Part 1
  .goreleaser.yml
  build.ps1
  build.sh
  cmd/new/class/class.go
  cmd/new/class/class_test.go
  cmd/new/definedtype/definedtype.go
  cmd/new/definedtype/definedtype_test.go
  cmd/new/fact/fact.go
  cmd/new/fact/fact_test.go
  cmd/new/function/function.go
  cmd/new/function/function_test.go
  cmd/new/module/module.go
  cmd/new/module/module_test.go
  cmd/new/new.go
  cmd/new/new_test.go
  cmd/new/provider/provider.go
  cmd/new/provider/provider_test.go
  cmd/new/task/task.go
  cmd/new/task/task_test.go
  cmd/new/test/test.go
  cmd/new/test/test_test.go
  cmd/new/transport/transport.go
  cmd/new/transport/transport_test.go
  cmd/root/root.go
  cmd/test/unit/unit.go
  cmd/version/version.go
  go.mod
  go.sum
  internal/pkg/pct/pct.go
  internal/pkg/pct/pct_test.go
  internal/pkg/pct/testdata/examples/full-project/content/metadata.json.tmpl
  internal/pkg/pct/testdata/examples/full-project/pct-config.yml
  internal/pkg/pct/testdata/examples/good-project/content/goodfile.txt.tmpl
  internal/pkg/pct/testdata/examples/good-project/pct-config.yml
  internal/pkg/pct/testdata/examples/replace-thing/content/{{pct_name}}.txt.tmpl
  internal/pkg/pct/testdata/examples/replace-thing/pct-config.yml
  main.go
Labels: enhancement

#35 (maint) Update Changelog
  CHANGELOG.md
Labels: maintenance

#36 (maint) Add bug report issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: maintenance

#40 (GH-29) Error if template not found
  CHANGELOG.md
  cmd/new/new.go
  internal/pkg/pct/pct.go
  internal/pkg/pct/pct_test.go
Labels: bug

#37 (maint) Pull request template
  .github/pull_request_template.md
Labels: maintenance

#38 (maint) Align build scripts
  .github/workflows/release.yml
  .goreleaser.yml
  CONTRIBUTING.md
  build.ps1
  build.sh
Labels: maintenance

#34 (GH-27) fix creation path of 'item' templates
  .gitignore
  cmd/new/new.go
  internal/pkg/pct/pct.go
  internal/pkg/pct/pct_test.go
Labels: bug

#25 (GH-23) Initial docs for PCT
  docs/pct/README.md
Labels: documentation

#42 (GH-28) Add acceptance testing example and utility functions
  .github/workflows/acceptance.yml
  CONTRIBUTING.md
  acceptance/new_test.go
  acceptance/testutils/testutils.go
  go.mod
Labels: enhancement

#44 (GH-20) Update docs/pct/README.md for PCT LA functionality
  docs/pct/README.md
Labels: documentation

#41 (GH-20) Bundle pct-templates with pkg
  .github/workflows/acceptance.yml
  .github/workflows/release.yml
  .goreleaser.yml
  build.ps1
  build.sh
  cmd/new/new.go
  internal/pkg/pct/pct.go
Labels: enhancement

#59 (maint) Fix new completion
  cmd/new/new.go
Labels: bug

#61 (GH-43) Add info flag to pct new
  acceptance/new_test.go
  cmd/new/new.go
  go.mod
  internal/pkg/pct/pct.go
  internal/pkg/pct/pct_test.go
Labels: enhancement

#69 (MAINT) Tweaks for release / build workflows
  .github/workflows/release.yml
  .gitignore
  build.ps1
  build.sh
Labels: maintenance

#70 (MAINT) Add GOPATH ENV var to release.yml
  .github/workflows/release.yml
Labels: maintenance
